2025-03-10 15:39:37,465 - nisto - INFO - Starting Network Topology Designer
2025-03-10 15:39:37,952 - nisto - ERROR - Unhandled exception in main
Traceback (most recent call last):
  File "/home/cam/Desktop/NISTO/network-topology-designer/src/main.py", line 63, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cam/Desktop/NISTO/network-topology-designer/src/main.py", line 54, in main
    main_window = MainWindow()
                  ^^^^^^^^^^^^
  File "/home/cam/Desktop/NISTO/network-topology-designer/src/controllers/main_window.py", line 26, in __init__
    self.device_manager = DeviceManager(self.scene)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceManager.__init__() takes 1 positional argument but 2 were given
